name : Artifact
on : [push]
env:
    ARTIFACT_NAME: myartifact
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2.0.0
            - name: Upload the artifact
              uses: actions/upload-artifact@v2
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: .  # The dot (.) represents the root directory of the repository.

