name : Complex
on : [push]
jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - run: date
    windows:
        runs-on : windows-latest
        steps:
            - run: date
    macos:
        runs-on : macos-latest
        steps:
            - run: date
    depends:
        needs: [ubuntu, windows, macos] # The needs key specifies the jobs that must complete successfully before the current job can run.
        runs-on : macos-latest
        steps:
            - run: date