
name : "Hello World"
on : [push] # The on key tells GitHub Actions to run the workflow every time a push event is triggered.
jobs :  # The jobs key contains a list of jobs that are run in parallel.
    say-hello : # The say-hello key is the name of the job.
        runs-on : ubuntu-latest # The runs-on key specifies the type of machine that the job runs on.
        steps: # The steps key contains a list of steps that are executed in order.
            - name : Checkout  # The name key is the name of the step.
              uses : actions/checkout@v2.0.0 # The uses key is the action that is executed in the step, they are 
              # typically docker images, a public repo, or a file in the same repository as the workflow file.
            - run: echo Hello, world! # The run key is the command that is executed in the step.


